-- CreateEnum
CREATE TYPE "ACCPETANCE_STATUS" AS ENUM ('ACCEPTED', 'REJECTED', 'PENDING');

-- AlterTable
ALTER TABLE "RentedCar" ADD COLUMN     "status" "ACCPETANCE_STATUS" NOT NULL DEFAULT 'PENDING';
