import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import ReduxProvider from 'src/redux/provider';

const sans = Plus_Jakarta_Sans({
	subsets: ['latin'],
	weight: ['300', '400', '700'],
	style: ['normal', 'italic'],
});

export const metadata: Metadata = {
	title: 'Welcome',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${sans.className}`}>
				<ReduxProvider>
					<section className="relative">
						{children}
					</section>
				</ReduxProvider>
			</body>
		</html>
	);
}
