import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import ReduxProvider from 'src/redux/provider';
import Header from '../components/Header';

const poppins_italic = Poppins({
	weight: '300',
	style: 'normal',
	subsets: ['devanagari'],
});

export const metadata: Metadata = {
	title: 'Welcome',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${poppins_italic.className}`}>
				<ReduxProvider>
					<Header />
					{children}
				</ReduxProvider>
			</body>
		</html>
	);
}
