import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins_italic = Poppins({
	weight: '300',
	style: 'normal',
	subsets: ['devanagari'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={poppins_italic.className}>{children}</body>
		</html>
	);
}
